FROM ubuntu:26.04

RUN apt-get update && \
    apt-get -y install \
        build-essential \
        libadwaita-1-dev \
        libgtk-4-dev \
        meson

RUN apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

RUN userdel -f -r ubuntu
