FROM fedora:45

# Install Free and Nonfree RPM Fusion Repositories
RUN dnf -y install \
        https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-45.noarch.rpm \
        https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-45.noarch.rpm

# Install additional codec
RUN dnf -y install \
        @multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin

RUN dnf -y install \
        blueprint-compiler \
        clang-tools-extra \
        desktop-file-utils \
        gtk4-devel \
        libadwaita-devel \
        meson \
        webkitgtk6.0-devel \
        yaru-theme
