FROM fedora:45

RUN dnf -y update && \
    dnf -y install \
        clang-tools-extra \
        blueprint-compiler \
        gtk4-devel \
        libadwaita-devel \
        meson \
        webkitgtk6.0-devel \
        yaru-theme
